### ISSUE TITLE
How to filter results

### ISSUE THREAD

**Issue by SimpleSenpai12** [freezegr/anime.js#2]
Whenever I run the _searchManga_ function (and I assume that this would give the same style of results for the other functions), my console automagically fills up with my search results. Is there a way to be able to filter search results? I'm making a Discord MessageEmbed for a bot.)

**Comment by freezegr** [comment]
> Whenever I run the _searchManga_ function (and I assume that this would give the same style of results for the other functions), my console automagically fills up with my search results. Is there a way to be able to filter search results? I'm making a Discord MessageEmbed for a bot.)

In a few days i will make an update wait until then.

**Comment by SimpleSenpai12** [comment]
ok!

**Comment by freezegr** [comment]
Sorry my guy,i have a problem with my account so it will take significantly more time

**Comment by freezegr** [comment]
https://www.npmjs.com/package/@freezegold/anime.js new update

**Comment by SimpleSenpai12** [comment]
thank you _**SO MUCH**_

**Comment by freezegr** [comment]
In a few days i will make an update for seasonal anime!
